email: minnullin.artur@gmail.com
description: >
  Artur Minnullin's personal website. Ruby on Rails, Javascript development.

social:
  - icon: github
    url:  https://github.com/ArturMinnullin

  - icon: linkedin
    url:  https://www.linkedin.com/in/arturminnullin

  - icon: vk
    url:  http://vk.com/artur_min

  - icon: at
    url:  mailto:minnullin.artur@gmail.com

kramdown:
  input: GFM
  coderay_line_numbers: nil

gems:
  - jemoji
  - jekyll-language-plugin

languages: ["en", "ru"]
language_data: data.lang.%%
language_includes_dir: _i18n
